apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-metadata
data:
  metadata.json: |
      {
        "USE_AGG_MDS": "{{ .Values.USE_AGG_MDS }}",
        "AGG_MDS_NAMESPACE": "{{ .Values.AGG_MDS_NAMESPACE }}"
      }