apiVersion: v1
kind: Service
metadata:
  name: "metadata-service"
  {{- with .Values.serviceAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "metadata.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.port }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  type: {{ .Values.service.type }}