apiVersion: v1
kind: ConfigMap
metadata: 
  name: revproxy-nginx-subconf
data:
{{- range $path, $bytes := .Files.Glob "gen3.nginx.conf/*.conf" }}
  {{ ($a := split "/" $path)._1 }}: |
  {{- $bytes | toString | nindent 4 }}  
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: revproxy-nginx-conf
data:
{{- range $path, $bytes := .Files.Glob "nginx/*" }}
  {{ ($a := split "/" $path)._1 }}: |
  {{- $bytes | toString | nindent 4 }}  
{{- end}}