apiVersion: v1
kind: Secret
metadata:
  name: ssjdispatcher-creds
type: Opaque
stringData:
  credentials.json: |-
    {
    "SQS": {
      "url": {{ .Values.ssjcreds.sqsUrl | quote }}
    },
    "JOBS": [
      {
        "name": {{ .Values.ssjcreds.jobName | quote }},
        "pattern": "{{ .Values.ssjcreds.jobPattern }}",
        "imageConfig": {
          "url": "{{ .Values.ssjcreds.jobUrl }}",
          "username": "{{ .Values.ssjcreds.jobUser }}",
          "password": "{{ .Values.ssjcreds.jobPassword }}",
          "metadataService": {
            "url": "{{ .Values.ssjcreds.metadataserviceUrl }}",
            "username": "{{ .Values.ssjcreds.metadataserviceUsername }}",
            "password": "{{ .Values.ssjcreds.metadataservicePassword }}"
          }
        },
        "RequestCPU": "{{ .Values.ssjcreds.jobRequestCpu }}",
        "RequestMem": "{{ .Values.ssjcreds.jobRequestMem }}"
      }
    ]
    }
