apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: gen3-dev
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-21T12:21:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: revproxy-dev
  namespace: default
  resourceVersion: "11765"
  uid: ea092060-74ff-4f0c-8ce0-fa7e70273e8e
spec:
  ingressClassName: traefik
  rules:
  - host: gen3local.co.za
    http:
      paths:
      - backend:
          service:
            name: revproxy-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: gen3-certs
status:
  loadBalancer:
    ingress:
    - ip: 10.0.2.238
