apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revproxy-dev
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: gen3-dev.core.wits.ac.za
    http:
      paths:
      - backend:
          service:
            name: revproxy-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: gen3-certs
