apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revproxy-dev
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: cloud08.core.wits.ac.za
    http:
      paths:
      - backend:
          service:
            name: revproxy-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.gen3-sbimb.com
    http:
      paths:
      - backend:
          service:
            name: revproxy-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: gen3-sbimb.com
    http:
      paths:
      - backend:
          service:
            name: revproxy-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cloud08.core.wits.ac.za
    secretName: cloud08-tls-secret
  - hosts:
    - gen3-sbimb.com
    secretName: gen3-sbimb-secret
  - hosts:
    - www.gen3-sbimb.com
    secretName: gen3-sbimb-secret
