apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: gen3-dev
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/managed-by: Helm
  name: revproxy-dev
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: cloud08.core.wits.ac.za
    http:
      paths:
      - backend:
          service:
            name: revproxy-service
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: revproxy-service
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - secretName: gen3-certs
