global:
  dev: true
  postgres:
    dbCreate: true
    master:
      username: postgres
      password: gen3-password
      host:
      port: "5432"
  # -- (string) Environment name.
  # This should be the same as vpcname if you're doing an AWS deployment.
  # Currently this is being used to share ALB's if you have multiple namespaces in same cluster.
  # environment: default
  # -- (string) Hostname for the deployment.
  hostname: cloud08.core.wits.ac.za
  # -- (string) ARN of the reverse proxy certificate.
  revproxyArn: arn:aws:acm:us-east-1:123456:certificate
  # -- (string) URL of the data dictionary.
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
  # -- (string) Portal application name.
  portalApp: gitops
  # -- (bool) Whether public datasets are enabled.
  publicDataSets: true
  # -- (string) Access level for tiers. acceptable values for `tier_access_level` are: `libre`, `regular` and `private`. If omitted, by default common will be treated as `private`
  tierAccessLevel: libre
  # -- (int) Only relevant if tireAccessLevel is set to "regular". Summary charts below this limit will not appear for aggregated data.
  tierAccessLimit: 1000
  # -- (bool) Whether network policies are enabled.
  netPolicy: true
  # -- (int) Number of dispatcher jobs.
  dispatcherJobNum: 10
  # -- (bool) Whether Datadog is enabled.
  ddEnabled: false

# Dependency Charts
ambassador:
  enabled: true
  image:
    # repository: quay.io/datawire/ambassador
    repository:
    tag:

arborist:
  enabled: true
  image:
    repository: quay.io/cdis/arborist
    pullPolicy: IfNotPresent
    tag: "master"

argo-wrapper:
  enabled: true
  image:
    repository: quay.io/cdis/argo-wrapper
    tag: "master"

audit:
  enabled: true
  image:
    repository: quay.io/cdis/audit-service
    tag: "master"
  dbRestore: false
  postgres:
    password: "gen3-password"

aws-es-proxy:
  enabled: false
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: "master"
  esEndpoint: test.us-east-1.es.amazonaws.com
  secrets:
    awsAccessKeyId: ""
    awsSecretAccessKey: ""

fence:
  enabled: true
  image:
    repository: quay.io/cdis/fence
    pullPolicy: Always
    tag: "master"
  dbRestore: false
  postgres:
    password: "gen3-password"
  # -- (map) Configuration settings for Fence app
  FENCE_CONFIG:
    APP_NAME: 'Gen3 Data Commons with K3s'
    OPENID_CONNECT:
      google:
        client_id: ""
        client_secret: ""
        # MOCK_AUTH: true
    AWS_CREDENTIALS:
      "gen3-user":
        aws_access_key_id: ""
        aws_secret_access_key: ""
    S3_BUCKETS:
      gen3-bucket:
        cred: "gen3-user"
        endpoint_url: "s3.us-east-1.amazonaws.com"
        region: 'us-east-1'
    DATA_UPLOAD_BUCKET: "gen3-bucket"
  # -- (string) USER YAML. Passed in as a multiline string.
  USER_YAML:
  # -- (map) Configuration options for usersync cronjob.
  usersync:
    # -- (bool) Whether to run Fence usersync or not.
    usersync: false
    # -- (map) Secret information
    secrets:
      # -- (str) AWS access key ID for usersync S3 bucket
      awsAccessKeyId: ""
      # -- (str) AWS secret access key for usersync S3 bucket
      awsSecretAccessKey: ""
    # -- (string) The cron schedule expression to use in the usersync cronjob. Runs every 30 minutes by default.
    schedule: "*/30 * * * *"
    # -- (string) To set a custom image for pulling the user.yaml file from S3. Default is the Gen3 Awshelper image.
    custom_image:
    # -- (bool) Whether to sync data from dbGaP.
    syncFromDbgap: false
    # -- (bool) Force attempting a dbgap sync if "true", falls back on user.yaml
    addDbgap: false
    # -- (bool) Forces ONLY a dbgap sync if "true", IGNORING user.yaml
    onlyDbgap: false
    # -- (string) Path to the user.yaml file in S3.
    userYamlS3Path: s3://cdis-gen3-users/helm-test/user.yaml
    # -- (string) Slack webhook endpoint used with certain jobs.
    slack_webhook: None
    # -- (bool) Will echo what files we are seeing on dbgap ftp to Slack.
    slack_send_dbgap: false

guppy:
  esEndpoint: "146.141.240.78:9200"
  tierAccessLimit: "1000"
  enabled: false
  image:
    repository: quay.io/cdis/guppy
    tag: "master"
  dbRestore: false
  postgres:
    password: "gen3-password"

hatchery:
  enabled: true
  image:
    repository: quay.io/cdis/hatchery
    tag: "master"
  hatchery:
    sidecarContainer:
      # -- (string) The maximum amount of CPU the sidecar container can use
      cpu-limit: '0.1'
      # -- (string) The maximum amount of memory the sidecar container can use
      memory-limit: 256Mi
      # -- (string) The sidecar image.
      image: quay.io/cdis/ecs-ws-sidecar:master
      # -- (map) Environment variables to pass to the sidecar container
      env:
        NAMESPACE: "{{ .Release.Namespace }}"
        HOSTNAME: "{{ .Values.global.hostname }}"
      # -- (list) Arguments to pass to the sidecare container.
      args: []
      # -- (list) Commands to run for the sidecar container.
      command:
      - "/bin/bash"
      - "./sidecar.sh"
      lifecycle-pre-stop:
      - su
      - "-c"
      - echo test
      - "-s"
      - "/bin/sh"
      - root
    containers:
    - # -- (int) port to proxy traffic to in docker container
      target-port: 8888
      # -- (string) cpu limit of workspace container
      cpu-limit: '1.0'
      # -- (string) memory limit of workspace container
      memory-limit: 2Gi
      # -- (string) name of workspace
      name: "(Tutorials) Example Analysis Jupyter Lab Notebooks"
      # -- (string) docker image for workspace
      image: quay.io/cdis/heal-notebooks:combined_tutorials__latest
      # -- environment variables for workspace container
      env:
        FRAME_ANCESTORS: https://{{ .Values.global.hostname }}
      args:
      - "--NotebookApp.base_url=/lw-workspace/proxy/"
      - "--NotebookApp.default_url=/lab"
      - "--NotebookApp.password=''"
      - "--NotebookApp.token=''"
      - "--NotebookApp.shutdown_no_activity_timeout=5400"
      - "--NotebookApp.quit_button=False"
      command:
      - start-notebook.sh
      path-rewrite: "/lw-workspace/proxy/"
      use-tls: 'false'
      ready-probe: "/lw-workspace/proxy/"
      lifecycle-post-start:
      - "/bin/sh"
      - "-c"
      - export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found; ln -s /data /home/$IAM/pd/; true
      user-uid: 1000
      fs-gid: 100
      user-volume-location: "/home/jovyan/pd"
      gen3-volume-location: "/home/jovyan/.gen3"

indexd:
  enabled: true
  image:
    repository: quay.io/cdis/indexd
    tag: "master"
  dbRestore: false
  postgres:
    password: ""

manifestservice:
  enabled: true
  image:
    repository: quay.io/cdis/manifestservice
    tag: "master"

metadata:
  enabled: true
  image:
    repository: quay.io/cdis/metadata-service
    tag: "master"

peregrine:
  enabled: true
  image:
    repository: quay.io/cdis/peregrine
    pullPolicy: IfNotPresent
    tag: ""

pidgin:
  enabled: true
  image:
    repository: quay.io/cdis/pidgin
    pullPolicy: Always
    tag: "master"

portal:
  enabled: true
  image:
    repository: quay.io/cdis/data-portal
    pullPolicy: Always
    tag: "master"

gitops:
  # -- (string) multiline string - gitops.json
  json:
  # -- (string) - favicon in base64
  favicon:
  # -- (string) - multiline string - gitops.css
  css:
  # -- (string) - logo in base64
  logo:
  # -- (string) - createdby.png - base64
  createdby:
  sponsors:


requestor:
  enabled: true
  image:
    repository: quay.io/cdis/requestor
    tag: "master"

revproxy:
  enabled: true
  image:
    repository:
    tag:
  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- (list) Where to route the traffic.
    hosts:
    - host: chart-example.local
    # -- (list) To secure an Ingress by specifying a secret that contains a TLS private key and certificate.
    tls: []

sheepdog:
  enabled: true
  image:
    repository: quay.io/cdis/sheepdog
    tag: "master"
  dbRestore: false
  postgres:
    password: "gen3-password"

ssjdispatcher:
  enabled: false
  image:
    repository: quay.io/cdis/ssjdispatcher
    tag: "master"

wts:
  enabled: true
  image:
    repository: quay.io/cdis/workspace-token-service
    pullPolicy: Always
    tag: "feat_wts_internalfence"

secrets:
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
