kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sower-binding
subjects:
- kind: ServiceAccount
  name: {{ include "sower.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io