apiVersion: v1
kind: Secret
metadata:
  name: aws-config-fence
type: Opaque
stringData:
  credentials: |
        [default]
        aws_access_key_id={{.Values.usersync.secrets.awsAccessKeyId}}
        aws_secret_access_key={{.Values.usersync.secrets.awsSecretAccessKey}}