apiVersion: v1
kind: Secret
metadata:
  name: fence-secret
type: Opaque
data:
{{ (.Files.Glob "fence-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fence-google-app-creds-secret
type: Opaque
data:
{{ (.Files.Glob "fence-google-creds/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fence-google-storage-creds-secret
type: Opaque
data:
{{ (.Files.Glob "fence-google-creds/*").AsSecrets | indent 2 }}
