apiVersion: v1
kind: Service
metadata:
  name: indexd-service
  labels:
    {{- include "indexd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "indexd.selectorLabels" . | nindent 4 }}
