apiVersion: v1
kind: Service
metadata:
  name: "argo-wrapper-service"
  labels:
    {{- include "argo-wrapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "argo-wrapper.selectorLabels" . | nindent 4 }}
