apiVersion: v1
kind: Secret
metadata:
  name: minio-dev
  namespace: "minio-dev"
  labels:
    app.kubernetes.io/instance: minio-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.2.26
    helm.sh/chart: minio-13.7.0
type: Opaque
data:
  root-user: "YWRtaW4="
  root-password: "Y0s0UHliWmJUTQ=="
