apiVersion: v1
kind: Secret
metadata:
  name: aws-es-proxy
type: Opaque
stringData:
  credentials: |
        [default]
        aws_access_key_id={{.Values.secrets.awsAccessKeyId}}
        aws_secret_access_key={{ .Values.secrets.awsSecretAccessKey}}