apiVersion: v2
appVersion: master
dependencies:
- name: common
  repository: file://../common
  version: 0.1.8
- condition: postgres.separate
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.13
- condition: elasticsearch.separate
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.1
description: A Helm chart for gen3 Metadata Service
name: metadata
type: application
version: 0.1.9
