apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: gen3-dev
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-11T21:35:12Z"
  generation: 1
  labels:
    app: indexd
    app.kubernetes.io/instance: gen3-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: indexd
    app.kubernetes.io/part-of: S3-GS
    app.kubernetes.io/version: 0.1.11
    critical-service: "true"
    release: production
  name: indexd-deployment
  namespace: default
  resourceVersion: "257984"
  uid: 9056e34b-9afe-45a9-9732-959a189433d4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexd
      app.kubernetes.io/instance: gen3-dev
      app.kubernetes.io/name: indexd
      release: production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: indexd
        app.kubernetes.io/instance: gen3-dev
        app.kubernetes.io/name: indexd
        release: production
    spec:
      containers:
      - env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: host
              name: indexd-dbcreds
              optional: false
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: username
              name: indexd-dbcreds
              optional: false
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: indexd-dbcreds
              optional: false
        - name: PGDB
          valueFrom:
            secretKeyRef:
              key: database
              name: indexd-dbcreds
              optional: false
        - name: DBREADY
          valueFrom:
            secretKeyRef:
              key: dbcreated
              name: indexd-dbcreds
              optional: false
        - name: DEFAULT_PREFIX
          value: PREFIX/
        - name: ARBORIST
          value: "true"
        - name: GEN3_DEBUG
          value: "False"
        image: quay.io/cdis/indexd:master
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_status
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: indexd
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_status
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 12Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/uwsgi/uwsgi.ini
          name: uwsgi-config
          subPath: uwsgi.ini
        - mountPath: /var/www/indexd/local_settings.py
          name: config-volume
          readOnly: true
          subPath: local_settings.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: indexd-uwsgi
        name: uwsgi-config
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: indexd-settings
