apiVersion: v1
kind: Secret
metadata:
  name: manifestservice-g3auto
type: Opaque
stringData:
  config.json: |-
      {
        "manifest_bucket_name": "{{ .Values.manifestserviceG3auto.bucketName }}",
        "hostname": "{{ .Values.manifestserviceG3auto.hostname }}",
        "aws_access_key_id": "{{ .Values.manifestserviceG3auto.awsaccesskey }}",
        "aws_secret_access_key": "{{ .Values.manifestserviceG3auto.awssecretkey }}",
        "prefix": "{{ .Values.manifestserviceG3auto.prefix }}"
      }

