apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-system
spec:
  selector:
    app: minio
  ports:
  - name: s3
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: NodePort
