apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-system
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      nodeSelector:
        kubernetes.io/hostname: cloud08
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9001
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
          hostPort: 9001
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ROOT_USER
          value: "minio_root_user"
        - name: MINIO_ROOT_PASSWORD
          value: "minio_root_password"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        resources:
          requests:
            memory: "1200Mi"
            cpu: "1500m"
          limits:
            memory: "1500Mi"
            cpu: "2000m"
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      restartPolicy: Always
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
        # hostPath: # not recommended for production, instead use an NFS Share or Amazon EBS
        #   path: $/HOME/workspace/gen3-volume # Specify a path to a local drive or volume on the Kubernetes worker node
        #   type: DirectoryOrCreate # The path to the `hostPath.path` directory must exist
