apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
  - ReadWriteOnce # ReadWriteOncePod is recommended for production
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
