{{- if or (.Values.secrets.awsSecretAccessKey) (.Values.global.aws.awsSecretAccessKey ) }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-config-guppy
type: Opaque
stringData:
  credentials: |
        [default]
        aws_access_key_id={{ .Values.secrets.awsAccessKeyId | default .Values.global.aws.awsAccessKeyId  }}
        aws_secret_access_key={{  .Values.secrets.awsSecretAccessKey | default .Values.global.aws.awsSecretAccessKey }}
{{- end }}

