apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-guppy
data:
  guppy_config.json: |
      {
        "indices": {{ .Values.indices  | toJson }},
        {{- with .Values.configIndex }}
        "config_index": {{ . | quote }},
        {{- end }}
        "auth_filter_field": {{ .Values.authFilterField | quote }},
        "enable_encrypt_whitelist": {{ .Values.enableEncryptWhitelist | quote }},
        "encrypt_whitelist":  {{ .Values.encryptWhitelist | quote }}
      }